# Generated by Django 4.2.4 on 2023-11-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
